
services:

  reservation_db:
    image: postgres:15-alpine
    container_name: reservation_db_container
    environment:
      POSTGRES_USER : ${RESERVATION_DB_USER}
      POSTGRES_PASSWORD : ${RESERVATION_DB_PASSWORD}
      POSTGRES_DB : ${RESERVATION_DB}

    volumes:
      - reservation_db_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"
volumes:
  reservation_db_data: